version: 2.0

jobs:
  "j1":
    machine:
      image: circleci/classic:201808-01
    working_directory: ~/circletest
    steps:
    - checkout
    - run: echo $CIRCLE_JOB

  "j2":
    machine:
      image: circleci/classic:201808-01
    working_directory: ~/circletest
    steps:
    - checkout
    - run: echo $CIRCLE_JOB

  "j3":
    machine:
      image: circleci/classic:201808-01
    working_directory: ~/circletest
    steps:
    - checkout
    - run: echo $CIRCLE_JOB

workflows:
  version: 2
  build:
    jobs:
    - "j1"
    - "j2"
    - "j3"