version: 2.0

jobs:

  "buildjob":
    machine:
      image: circleci/classic:201808-01
    working_directory: ~/circletest
    steps:
    - checkout
    - run: echo $CIRCLE_JOB
    - run: echo $CIRCLE_JOB >.circle_build_job.txt
    - run: echo "PWD=$PWD" && ls -laR $PWD
    persist_to_workspace:
      root: ~/
      paths: circletest

  "j1":
    working_directory: ~/circletest
    attach_workspace:
      at: ~/
    machine:
      image: circleci/classic:201808-01
    requires:
      - build
    steps:
    - run: echo "PWD=$PWD" && ls -laR ~
    - run: echo "CIRCLE_JOB=$CIRCLE_JOB and build_job=$(cat .circle_build_job.txt)"

#  "j2":
#    machine:
#      image: circleci/classic:201808-01
#    working_directory: ~/circletest
#    steps:
#    - run: echo $CIRCLE_JOB
#
#  "j3":
#    machine:
#      image: circleci/classic:201808-01
#    working_directory: ~/circletest
#    steps:
#    - run: echo $CIRCLE_JOB


workflows:
  version: 2
  test:
    jobs:
    - "buildjob"
    - "j1"
#    - "j2"
#    - "j3"